schema_version = "1.0.0"

id = "Rova_Tools"
version = "1.0.0"
name = "Rova Tools"
tagline = "Helps Create Rova"
maintainer = "Glen Pearce"
# Supported types: "add-on"
type = "add-on"

# Optional link to documentation, support, source files, etc
# website = "insert docs when made"

tags = ["Modeling"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
license = ["SPDX:GPL-2.0-or-later"]